countries:
  enabled:
    - "All Jurisdictions"
    - "Afghanistan"
    - "Argentina"
    - "Australia"
    - "Austria"
    - "Azerbaijan"
    - "Bahrain"
    - "Bangladesh"
    - "Belarus"
    - "Belgium"
    - "Bolivia (Plurinational State of)"
    - "Brazil"
    - "Bulgaria"
    - "Cambodia"
    - "Cameroon"
    - "Canada"
    - "Chile"
    - "China"
    - "Colombia"
    - "Costa Rica"
    - "Croatia"
    - "Cyprus"
    - "Czechia"
    - "Denmark"
    - "Dominican Republic"
    - "Ecuador"
    - "Egypt"
    - "Equatorial Guinea"
    - "Estonia"
    - "Fiji"
    - "Finland"
    - "France"
    - "Germany"
    - "Greece"
    - "Guatemala"
    - "Guyana"
    - "Honduras"
    - "Hungary"
    - "Iceland"
    - "India"
    - "Indonesia"
    - "Iraq"
    - "Ireland"
    - "Israel"
    - "Italy"
    - "Japan"
    - "Jordan"
    - "Kazakhstan"
    - "Kenya"
    - "Kuwait"

  disabled:
    - "Albania"
    - "Algeria"
    - "Andorra"
    - "Angola"
    - "Antigua and Barbuda"
    - "Armenia"
    - "Bahamas"
    - "Barbados"
    - "Belize"
    - "Benin"
    - "Bhutan"
    - "Bosnia and Herzegovina"
    - "Botswana"
    - "Brunei Darussalam"
    - "Burkina Faso"
    - "Burundi"
    - "Cabo Verde"
    - "Central African Republic"
    - "Chad"
    - "Comoros"
    - "Congo"
    - "Cook Islands"
    - "Côte d'Ivoire"
    - "Cuba"
    - "Democratic People's Republic of Korea"
    - "Democratic Republic of the Congo"
    - "Djibouti"
    - "Dominica"
    - "El Salvador"
    - "Eritrea"
    - "Eswatini"
    - "Ethiopia"
    - "Gabon"
    - "Gambia"
    - "Georgia"
    - "Ghana"
    - "Grenada"
    - "Guinea"
    - "Guinea-Bissau"
    - "Haiti"
    - "Holy See"
    - "Iran (Islamic Republic of)"
    - "Jamaica"
    - "Kiribati"
    - "Kyrgyzstan"
    - "Lao People's Democratic Republic"
    - "Latvia"
    - "Lebanon"
    - "Lesotho"
